version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: Duy_mc_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "56432:5432"
    volumes:
      - ./volumnes/postgres:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: Duy_mc_qdrant
    restart: always
    ports:
      - "56333:6333"
      - "56334:6334"
    volumes:
      - ./volumnes/qdrant:/qdrant/storage

  loki:
    image: grafana/loki:2.9.0
    container_name: Duy_mc_loki
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    ports:  
      - "56310:3100"
    volumes:
      - ./volumnes/loki:/loki

  grafana:
    image: grafana/grafana
    container_name: Duy_mc_grafana
    restart: always
    ports:
      - "56300:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volumnes/grafana:/var/lib/grafana

  ollama:
    image: ollama/ollama
    container_name: Duy_mc_ollama
    restart: always
    ports:
      - "56800:11434"
    volumes:
      - ./volumnes/ollama:/root/.ollama
